### ISSUE TITLE
Create a Yukon Basemap Component

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pcic-react-leaflet-components#1]
We have OSM tiles rendered in the Yukon Albers projection (EPSG:3578) available here:
https://services.pacificclimate.org/tiles_north/Z/X/Y.png

E.g.

![tiles north](https://services.pacificclimate.org/tiles_north/7/67/65.png)

Write a component that uses them. See [here](https://redmine.pcic.uvic.ca/issues/1295) and [here](https://redmine.pcic.uvic.ca/issues/1292) for technical details.

**Comment by rod-glover** [comment]
A `YNWTBaseMap` component now exists in a branch (it is a trivial adaptation of `BCBaseMap`). However, it needs as yet unknown values for the `Leaflet.Proj.CRS` constructor, specifically the following:

- `options.bounds`
  - defined in https://spatialreference.org/ref/epsg/3578/
  - may not matter

- `options.resolutions`
  - see https://gis.stackexchange.com/questions/153640/proj4leaflet-create-crs-scales-resolution-from-wmts-getcapacilities-scaledenomin/153645#153645
  - This requires the "scale denominator", the only known (to me) source of which is the output of a WTMS GetCapabilities request. Our tile server does not seem to offer this service.
  - see also https://enonline.supermap.com/iServer9D/Appendix/scale.htm

- `options.origin`
  - see https://gis.stackexchange.com/questions/352291/find-the-right-values-for-bounds-and-origin-for-proj4leaflet
  - Likewise, this requires the scale denominator.

The `options` are minimally documented [here](https://www.npmjs.com/package/proj4leaflet?activeTab=readme#constructor) or, equivalently, [here](https://kartena.github.io/Proj4Leaflet/api/).

**Comment by rod-glover** [comment]
Regarding `options.resolutions`: As noted above, this is closely tied to the value of a parameter called `scaleDenominator`. In fact, in Leaflet, the term "resolution" appears to be synonymous with `scaleDenominator`.

Parameter `scaleDenominator` is defined by the [OpenGIS Web Map Tile Service Implementation Standard](https://portal.ogc.org/files/?artifact_id=35326), section 6.1, as follows:

Briefly, a WTMS provides a tile matrix set.  A tile matrix set is composed of a collection of tile matrices, each one with a resolution optimized for a particular scale [i.e., zoom level].

Each tile matrix specifies the scale of the tiles as a _scale denominator_.

> The scale denominator is defined with respect to a "standardized rendering pixel size" of
> 0.28 mm × 0.28 mm (millimeters). The definition is the same used in WMS 1.3.0 [OGC
> 06-042] and in Symbology Encoding Implementation Specification 1.1.0 [05-077r4].
> Frequently, the true pixel size is unknown and 0.28 mm is a common actual size for
> current displays.

Here, we refer to this value as `pixelWidth` (= 0.00028).

The parameter `options.resolutions` to `Leaflet.CRS` is precisely sequence of `scaleDenominator * pixelWidth` values for each tile matrix in the set, from lowest zoom to highest.

Aside: Formally, there is one `scaleDenominator` per tile matrix. Since the tile matrices in a set are typically (as in the case of our Yukon Albers tile set) related by powers of 2 (each tile set's tiles are 1/2 the linear dimension of the next lower zoom level), the `scaleDenominator` for a single tile set (most conveniently, the zero-th zoom level) suffices to define them all.

Each tile matrix also specifies the top left (minimum x, maximum y) corner of the bounding box of the tile matrix
(i.e., the CRS coordinates of the top left corner of the top left pixel of the top left tile). 

The Standard gives the relationship between: 

- the `scaleDenominator`
- the coefficient to convert the coordinate reference system (CRS) units into meters (`metersPerUnit`) 
- the width and height of a tile in pixels (`tileWidth`, `tileHeight`)
- the width and height of a tile in CRS units (`tileSpanX`, `tileSpanY`)

as follows:

```
pixelSpan = scaleDenominator × 0.28 10-3 / metersPerUnit;
tileSpanX = tileWidth × pixelSpan;
tileSpanY = tileHeight × pixelSpan;
```

We do not appear to have any direct source for `scaleDenominator`. (It is exported directly in the `GetCapabilities` response of a WMTS but which does not appear to be available in our stack). However, if we can obtain values for the other parameters, we can compute `scaleDenominator` and hence the crucial `options.resolutions` parameter.

From the definition of the Yukon Albers projection, `metersPerUnit ` = 1.

QGIS tells us the other values. How exactly it "knows" these values is a mystery at the moment. To get them:

- In the Browser pane, define our `tiles_north` (Yukon Albers) tile set as an XYZ Tiles set (because this is what it is).
- Right click on the `tiles_north` tile set just added, and click Layer properties...
- Scroll down to the WMS info section, and to the table headed "Selected tile matrix set tms0".
- Parameters `tileWidth`, `tileHeight` are the columns Tile Size [px]; both = 256.
- Parameters tileSpanX`, `tileSpanY are the columns Matrix extent [mu]; both = 40075016.685578. 

We can calculate `scaleDenominator` from this information:

```
pixelSpan = tileSpanX / tileWidth = tileSpanY / tileHeight = 40075016.685578 / 256 = 156543.033928039;
scaleDenominator = pixelSpan * metersPerUnit / 0.00028 = 156543.033928039 * 1 / 0.00028 = 559082264.028711
```

This is the `scaleDenominator` for the zero-th zoom level. The `scaleDenominator` and resolution for zoom level `i` are computed as follows:

```
scaleDenominator[i] = scaleDenominator[0] / 2**i
resolution[i] = scaleDenominator[i] * pixelWidth = scaleDenominator[0] * pixelWidth / 2**i
```

**Comment by rod-glover** [comment]
# `options.origin`

This is defined in the [Proj4Leaflet documentation](https://github.com/kartena/Proj4Leaflet#readme) as 

> the projected coordinate to use as the map's pixel origin

Just exactly what this means is not instantly clear. But a little deducing and experimenting shows that it means the upper-left corner of the tile set, in projected coordinates. 

Again, QGIS to the rescue: In the Layer properties table headed "Selected tile matrix set tms0", we find columns Bounds Top and Left. These are in projected coordinates, so give us the values for origin (which takes the form of an array `[left, top]`); hence we have

```
origin = [-20037508.342789, 20037508.342789]
```

**Comment by rod-glover** [comment]
# `options.bounds`

This is defined in the [Proj4Leaflet documentation](https://github.com/kartena/Proj4Leaflet#readme) as 

> an `L.Bounds` providing the bounds of CRS in projected coordinates

This value is obtained from Layer properties table headed "Selected tile matrix set tms0", columns Bounds.

It is not necessary to specify this value, but given it is available, why not?

**Comment by rod-glover** [comment]
To summarize the knowledge to date:

1. Obtain the following information:
   - the coefficient to convert the coordinate reference system (CRS) units into meters (`metersPerUnit`) -- obtain from CRS definition
   - the width and height of a tile in pixels (`tileWidth`, `tileHeight`) -- obtain from tile mill, `GetCapabilities` request, or guesswork (256 is usual)
   - extents (bounds) of the tile set, in projected units, `tileMatrixMinX`, `tileMatrixMaxX`, `tileMatrixMinY`, `tileMatrixMaxY` -- obtain from tile mill or `GetCapabilities` request.

2. Compute
   ```
   pixelSpan = tileSpanX / tileWidth = tileSpanY / tileHeight;
   scaleDenominator0 = pixelSpan * metersPerUnit / pixelWidth;
   ```

3. Compute parameters for input to `L.Proj.CRS`:
   ```
   bounds = L.Bounds(
      L.Point(tileMatrixMinX, tileMatrixMinY),
      L.Point(tileMatrixMaxX, tileMatrixMaxY),
    )

   resolutions[i] = scaleDenominator0 * pixelWidth / 2**i

   origin = [tileMatrixMinX, tileMatrixMaxY]
   ```
